pipeline {
  environment {
    registry = "kuripka/nginx-lb"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
	git credentialsId: 'GitHub-SSHKey', url: 'https://github.com/kyripa/nginx-lb.git' 
     }
    }
    stage('Building image') {
      steps{
	sh "ls -l"
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}
